// JavaScript Document
	$(document).ready(function(){
		$(".A").click(function(){
			$(".tocA").fadeIn(1000);
			});
			$(".tocA").click(function(){
			$(this).fadeOut(1500);
			});
		$(".B").click(function(){
			$(".tocB").fadeIn(1000);
			});
			$(".tocB").click(function(){
			$(this).fadeOut(1500);
			});
		$(".C").click(function(){
			$(".tocC").fadeIn(1000);
			});
			$(".tocC").click(function(){
			$(this).fadeOut(1500);
			});
		$(".D").click(function(){
			$(".tocD").fadeIn(1000);
			});
			$(".tocD").click(function(){
			$(this).fadeOut(1500);
			});
		$(".E").click(function(){
			$(".tocE").fadeIn(1000);
			});
			$(".tocE").click(function(){
			$(this).fadeOut(1500);
			});
		$(".F").click(function(){
			$(".tocF").fadeIn(1000);
			});
			$(".tocF").click(function(){
			$(this).fadeOut(1500);
			});
		$(".G").click(function(){
			$(".tocG").fadeIn(1000);
			});
			$(".tocG").click(function(){
			$(this).fadeOut(1500);
			});
		$(".H").click(function(){
			$(".tocH").fadeIn(1000);
			});
			$(".tocH").click(function(){
			$(this).fadeOut(1500);
			});
		$(".I").click(function(){
			$(".tocI").fadeIn(1000);
			});
			$(".tocI").click(function(){
			$(this).fadeOut(1500);
			});
		$(".J").click(function(){
			$(".tocJ").fadeIn(1000);
			});
			$(".tocJ").click(function(){
			$(this).fadeOut(1500);
			});
		$(".K").click(function(){
			$(".tocK").fadeIn(1000);
			});
			$(".tocK").click(function(){
			$(this).fadeOut(1500);
			});
		$(".L").click(function(){
			$(".tocL").fadeIn(1000);
			});
			$(".tocL").click(function(){
			$(this).fadeOut(1500);
			});
		$(".M").click(function(){
			$(".tocM").fadeIn(1000);
			});
			$(".tocM").click(function(){
			$(this).fadeOut(1500);
			});
		$(".N").click(function(){
			$(".tocN").fadeIn(1000);
			});
			$(".tocN").click(function(){
			$(this).fadeOut(1500);
			});
		$(".O").click(function(){
			$(".tocO").fadeIn(1000);
			});
			$(".tocO").click(function(){
			$(this).fadeOut(1500);
			});
		$(".P").click(function(){
			$(".tocP").fadeIn(1000);
			});
			$(".tocP").click(function(){
			$(this).fadeOut(1500);
			});
		$(".Q").click(function(){
			$(".tocQ").fadeIn(1000);
			});
			$(".tocQ").click(function(){
			$(this).fadeOut(1500);
			});
		$(".R").click(function(){
			$(".tocR").fadeIn(1000);
			});
			$(".tocR").click(function(){
			$(this).fadeOut(1500);
			});
		$(".S").click(function(){
			$(".tocS").fadeIn(1000);
			});
			$(".tocS").click(function(){
			$(this).fadeOut(1500);
			});
		$(".T").click(function(){
			$(".tocT").fadeIn(1000);
			});
			$(".tocT").click(function(){
			$(this).fadeOut(1500);
			});
		$(".U").click(function(){
			$(".tocU").fadeIn(1000);
			});
			$(".tocU").click(function(){
			$(this).fadeOut(1500);
			});
		$(".V").click(function(){
			$(".tocV").fadeIn(1000);
			});
			$(".tocV").click(function(){
			$(this).fadeOut(1500);
			});
		$(".W").click(function(){
			$(".tocW").fadeIn(1000);
			});
			$(".tocW").click(function(){
			$(this).fadeOut(1500);
			});
		$(".X").click(function(){
			$(".tocX").fadeIn(1000);
			});
			$(".tocX").click(function(){
			$(this).fadeOut(1500);
			});
		$(".Y").click(function(){
			$(".tocY").fadeIn(1000);
			});
			$(".tocY").click(function(){
			$(this).fadeOut(1500);
			});
		$(".Z").click(function(){
			$(".tocZ").fadeIn(1000);
			});
			$(".tocZ").click(function(){
			$(this).fadeOut(1500);
			});
		$(".num1").click(function(){
			$(".tocNum1").fadeIn(1000);
			});
			$(".tocNum1").click(function(){
			$(this).fadeOut(1500);
			});
		$(".num2").click(function(){
			$(".tocNum2").fadeIn(1000);
			});
			$(".tocNum2").click(function(){
			$(this).fadeOut(1500);
			});
		$(".num3").click(function(){
			$(".tocNum3").fadeIn(1000);
			});
			$(".tocNum3").click(function(){
			$(this).fadeOut(1500);
			});
		$(".num4").click(function(){
			$(".tocNum4").fadeIn(1000);
			});
			$(".tocNum4").click(function(){
			$(this).fadeOut(1500);
			});
		$(".num5").click(function(){
			$(".tocNum5").fadeIn(1000);
			});
			$(".tocNum5").click(function(){
			$(this).fadeOut(1500);
			});
	});